### ISSUE TITLE
cf services examples not working

### ISSUE THREAD

**Issue by ttakach** [SUSE-Developer-Community/sandbox-welcome-content#113]
I have been unable to create or delete any cf services listed from the marketplace in the sandbox.
I have tried this with all of the mariadb, redis, and postgresql services and plans.
I even followed along step-by-step with the tutorial.
Creation fails and then I am unable to delete any of the failed services as well.

cf create-service redis 5-0-6 myredis
Creating service instance myredis in org... 
OK

Service myredis already exists
cf delete-service myredis

Really delete the service myredis?> yes
Deleting service myredis in org...
OK

Delete in progress. Use 'cf services' or 'cf service myredis' to check operation status.
cf services
Getting services in org...

name            service   plan      bound apps   last operation   broker          upgrade available
first-push-db   mariadb   10-3-21                delete failed    minibroker1.0   
myredis         redis     5-0-6                  delete failed    minibroker1.0   

I have not seen any updates to this thread since March.  Is the CAP sandbox CF tutorial still viable I just joined this past week.

**Comment by agracey** [comment]
Thank you for the heads up, looks like I needed to upgrade the minibroker instance to handle the unannounced depreciation of the old stable helm repo. 

Should be fixed now!

**Comment by ttakach** [comment]
> Thank you for the heads up, looks like I needed to upgrade the minibroker instance to handle the unannounced depreciation of the old stable helm repo.
> 
> Should be fixed now!
Thanks for the quick response.
But still unable to delete or create any services. Because I cannot delete any I have also hit a quota limit...

`
cf create-service redis 5-0-6 srvRedis
Creating service instance srvRedis in org...
You have exceeded your organization's services limit.
FAILED
cf delete-service myredis
Really delete the service myredis?> yes
Deleting service myredis in org ttakach_gmail_com / space dev as ttakach@gmail.com...
OK

Delete in progress. Use 'cf services' or 'cf service myredis' to check operation status.
cf services
Getting services in org...
name            service   plan      bound apps   last operation   broker          upgrade available
first-push-db   mariadb   10-3-21                delete failed    minibroker1.0   
myredis         redis     5-0-6                  delete failed    minibroker1.0  
`

**Comment by agracey** [comment]
Would you mind if I deleted your services as an admin (are there any that you need to keep?)

**Comment by agracey** [comment]
Reopening until resolved

**Comment by agracey** [comment]
I just tested a service creation with a non-admin user and it worked so I'm betting that it's an issue with the services not existing to be deleted. I should be able to delete them as an admin. 

Sorry for the frustration, I skipped an update that I shouldn't have...

**Comment by ttakach** [comment]
> Would you mind if I deleted your services as an admin (are there any that you need to keep?)

No not at all.  It was all just experimentation so far.

**Comment by cbela65** [comment]
I would not mind if you could delete my services as well.  I tried the purge process but it did not work since I am not an admin.

**Comment by agracey** [comment]
I believe that all of the affected services are purged now. Please let me know if there are any continuing issues

**Comment by cbela65** [comment]
I was able to create the service thank you!

**Comment by ttakach** [comment]
> I believe that all of the affected services are purged now. Please let me know if there are any continuing issues

It looks like it's working now.  Thanks! Have a great New Year!
